<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Bismillahirrahmanirrahim</name>
   <tag></tag>
   <elementGuidId>51946af4-22ad-49d5-9d9c-b9378a8929d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[text()='Bismillahirrahmanirrahim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()='Bismillahirrahmanirrahim']</value>
      <webElementGuid>60838a01-f18c-42ab-a993-6b3f9a014448</webElementGuid>
   </webElementProperties>
</WebElementEntity>
